module.exports = {
    USER_HELLO_EVENT: 'USER_HELLO_EVENT',
    USER_HELLOSUCCESS_EVENT: 'USER_HELLOSUCCESS_EVENT',
    USER_HELLOFAIL_EVENT: 'USER_HELLOFAIL_EVENT',
    USER_LEFT_EVENT: 'USER_LEFT_EVENT',
    USER_CHAT_EVENT: 'USER_CHAT_EVENT',
    USER_JOIN_EVENT: 'USER_JOIN_EVENT',
    GET_ONLINE_USERS: 'GET_ONLINE_USERS',
    USER_GOODBYE_EVENT: 'USER_GOODBYE_EVENT'
}
